### PR TITLE
Add graph visualization agent

### PR DESCRIPTION
**Pull request by AbanoubAbdelmalak**
This pull request is to solve issue #49 as follows:
* A new package called cell was added to contain the important elements for visualization.
* The locations are multiplied by 100 for better visualization.
* The visualization agent has three behaviors:
    * GraphBuilder:
        * Communicates with the transport networks and gets all the locations of the customers and the bakeries.
        * Rectangles shows the bakeries and triangles shows the customers.
        * All the edges are all drawn.
     * TruckTracker:
         * Communicates with all the trucks and get their location, orderID and time to deliver.
         * Shows the above data and each truck is a circle on the map.
     * JFXStart:
         * This behaviour creates a Thread to run the JavaFX application.

### CODE REVIEW

**Comment by AbanoubAbdelmalak** [comment]
@argenos The checks here were not successful as Travis can not recognize the JavaFX packages.
What should be done?

**Comment by AbanoubAbdelmalak** [comment]
@Sushant-Chavan, @AhmedFaisal95  What doe you think should be done for now? Create a pull request to the main project or should I wait?

**Comment by argenos** [comment]
Have you added them to gradle?

**Comment by Sushant-Chavan** [comment]
Like Argentina suggested, seems like you need to add a dependency to JavaFX similar to how we did it for JSON..

**Comment by Sushant-Chavan** [comment]
No longer needed since visualization agent has already been merged in the upstream develop branch

**Pull request closed without merging**
